export const occurrences = [
  {
    id: 1,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 2,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Tree',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 3,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 4,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Acacia',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 5,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Narra',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 6,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 7,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Tree',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 8,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Rose',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 9,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Cactus',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 10,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Grass',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 11,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Lily',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 12,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Lotus',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 13,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Rose',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 14,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Lily',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 15,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Lotus',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 16,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 17,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Acacia',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 18,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Narra',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 19,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Cactus',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 20,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Grass',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 21,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },

  {
    id: 22,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Lily',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 23,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Lotus',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 24,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 25,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Acacia',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 26,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Narra',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 27,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 28,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Tree',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 29,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Rose',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 30,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Cactus',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 31,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Grass',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 2,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Tree',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 32,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Rose',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 33,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Cactus',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 34,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Grass',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 35,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Lily',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 1,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Lotus',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 36,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 37,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Acacia',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 38,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Narra',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 39,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 40,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Tree',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 41,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Rose',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 42,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Cactus',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 43,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Grass',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 44,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Lily',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 45,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Lotus',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 46,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Orchid',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
  {
    id: 47,
    latitude: 1.3521,
    longitude: 103.8198,
    dateObserved: '2024-09-03',
    occurrenceStatus: 'ACTIVE',
    numberOfPlants: 150,
    dateOfBirth: '2024-01-10',
    biomass: 1200.5,
    occurrenceDescription: 'Mangrove restoration area',
    decarbonizationType: 'CARBON_SEQUESTRATION',
    speciesId: 1001,
    speciesName: 'Acacia',
    statusLogs: [
      {
        logId: 1,
        status: 'HEALTHY',
        dateLogged: '2024-02-15',
        remarks: 'Plants are growing well',
      },
      {
        logId: 2,
        status: 'MONITORED',
        dateLogged: '2024-03-10',
        remarks: 'Area requires periodic monitoring',
      },
    ],
    decarbonizationAreaId: 501,
  },
  {
    id: 48,
    latitude: 1.3644,
    longitude: 103.9915,
    dateObserved: '2024-09-02',
    occurrenceStatus: 'INACTIVE',
    numberOfPlants: 80,
    dateOfBirth: '2023-11-05',
    biomass: 850.2,
    occurrenceDescription: 'Urban tree planting project',
    decarbonizationType: 'URBAN_GREENING',
    speciesId: 1002,
    speciesName: 'Narra',
    statusLogs: [
      {
        logId: 1,
        status: 'SICK',
        dateLogged: '2024-08-20',
        remarks: 'Plants affected by disease',
      },
      {
        logId: 2,
        status: 'REPLANTED',
        dateLogged: '2024-08-25',
        remarks: 'Diseased plants have been replaced',
      },
    ],
    decarbonizationAreaId: 502,
  },
];
