export enum OccurrenceStatusEnum {
  HEALTHY = 'HEALTHY',
  MONITOR_AFTER_TREATMENT = 'MONITOR_AFTER_TREATMENT',
  NEEDS_ATTENTION = 'NEEDS_ATTENTION',
  URGENT_ACTION_REQUIRED = 'URGENT_ACTION_REQUIRED',
  REMOVED = 'REMOVED',
}

export enum PlantTaskStatusEnum {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum PlantTaskTypeEnum {
  INSPECTION = 'INSPECTION',
  WATERING = 'WATERING',
  PRUNING_TRIMMING = 'PRUNING_TRIMMING',
  PEST_MANAGEMENT = 'PEST_MANAGEMENT',
  SOIL_MAINTENANCE = 'SOIL_MAINTENANCE',
  STAKING_SUPPORTING = 'STAKING_SUPPORTING',
  DEBRIS_REMOVAL = 'DEBRIS_REMOVAL',
  ENVIRONMENTAL_ADJUSTMENT = 'ENVIRONMENTAL_ADJUSTMENT',
  OTHERS = 'OTHERS'
}

export enum PlantTaskUrgencyEnum {
  IMMEDIATE = 'IMMEDIATE',
  HIGH = 'HIGH',
  NORMAL = 'NORMAL',
  LOW = 'LOW'
}
export enum ParkAssetTypeEnum {
  EQUIPMENT_RELATED = 'EQUIPMENT_RELATED',
  PLANT_RELATED = 'PLANT_RELATED',
  PLANT_TOOL = 'PLANT_TOOL',
}

export enum ParkAssetStatusEnum {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum ParkAssetConditionEnum {
  EXCELLENT = 'EXCELLENT',
  FAIR = 'FAIR',
  POOR = 'POOR',
  DAMAGED = 'DAMAGED',
}
